### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by expl0s10n** [Gdeft/bleach#7]
just crashes

**Comment by Gdeft** [comment]
1. What do you mean by mobile.
2. Works for me.
3. Where is the crash log.
4. This is not helpful.
5. Try using the https://en.m.wikipedia.org/wiki/Brain

**Comment by expl0s10n** [comment]
> 1. What do you mean by mobile.
> 2. Works for me.
> 3. Where is the crash log.
> 4. This is not helpful.
> 5. Try using the https://en.m.wikipedia.org/wiki/Brain

1. I do not understand how to post crash logs.
2. Idk
3. Idk
4. Idk
5. Idk
6. Or do u mean like:
rhino.WrappedException: Wrapped java.lang.IllegalArgumentException: Failed to compile shader: Fragment shader:
ERROR: 0:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'FragCoord 4-component vector of float' and a right operand of type '2-component vector of float' (or there is no acceptable conversion)
ERROR: 0:16: '=' :  cannot convert from '4-component vector of float' to '2-component vector of float'
ERROR: 0:20: ';' : Syntax error:  syntax error
ERROR: 3 compilation errors.  No code generated.

 (main.js#25)
	at rhino.Context.throwAsScriptRuntimeEx(Context.java:1668)
	at rhino.MemberBox.newInstance(MemberBox.java:145)
	at rhino.NativeJavaClass.constructInternal(NativeJavaClass.java:251)
	at rhino.NativeJavaClass.constructSpecific(NativeJavaClass.java:192)
	at rhino.NativeJavaClass.construct(NativeJavaClass.java:155)
	at rhino.ScriptRuntime.newObject(ScriptRuntime.java:2451)
	at rhino.gen.main_js_35._c_anonymous_4(main.js:25)
	at rhino.gen.main_js_35.call(Unknown Source:59)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.main_js_35.call(Unknown Source:18)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0$InterfaceAdapter(InterfaceAdapter.java:92)
	at rhino.-$$Lambda$InterfaceAdapter$GS5pe0iB_uMmYJOoJRJ6I3mO2jU.run(Unknown Source:13)
	at rhino.Context.call(Context.java:524)
	at rhino.ContextFactory.call(ContextFactory.java:446)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.jdk18.VMBridge_jdk18.lambda$newInterfaceProxy$0(VMBridge_jdk18.java:100)
	at rhino.jdk18.-$$Lambda$VMBridge_jdk18$ggYMF9TpGNVQ1Biw8Nj4QDudM_c.invoke(Unknown Source:11)
	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
	at $Proxy2.get(Unknown Source)
	at arc.Events.lambda$fire$2(Events.java:30)
	at arc.-$$Lambda$Events$kEWEoJJ7iuVpyOJB9UfewcihGzY.get(Unknown Source:4)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:30)
	at arc.Events.fire(Events.java:25)
	at mindustry.ClientLauncher.update(ClientLauncher.java:146)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(Unknown Source:793)
	at android.opengl.GLSurfaceView$GLThread.run(Unknown Source:27)
Caused by: java.lang.IllegalArgumentException: Failed to compile shader: Fragment shader:
ERROR: 0:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'FragCoord 4-component vector of float' and a right operand of type '2-component vector of float' (or there is no acceptable conversion)
ERROR: 0:16: '=' :  cannot convert from '4-component vector of float' to '2-component vector of float'
ERROR: 0:20: ';' : Syntax error:  syntax error
ERROR: 3 compilation errors.  No code generated.


	at arc.graphics.gl.Shader.<init>(Shader.java:129)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at rhino.MemberBox.newInstance(MemberBox.java:137)
	... 29 more
